import copy
import json
import os
import struct
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from media import prepare, pcm_info, sha256, validate_manifest, verify_tail, write_pcm, SAMPLE_RATE


def fixture_manifest():
    return {
        "schemaVersion": 1,
        "source": {"url": "https://example.invalid/original", "license": "Original test material",
                   "licenseUrl": "https://example.invalid/license", "title": "Original tones",
                   "sha256": "a" * 64, "attribution": ["Generated by this deterministic test"]},
        "reference": {"humanVerified": False, "text": None},
        "clips": [{"id": "original-test", "startSeconds": 1, "endSeconds": 2, "speechEnd": None}],
    }


class MediaTests(unittest.TestCase):
    def test_manifest_valid(self):
        validate_manifest(fixture_manifest())

    def test_explicit_human_annotation(self):
        manifest = fixture_manifest()
        manifest["clips"][0]["speechEnd"] = {"kind": "human-annotated", "sourceSeconds": 1.8, "provenance": "Operator alignment"}
        validate_manifest(manifest)

    def test_duplicate_clip(self):
        m = fixture_manifest()
        m["clips"].append(copy.deepcopy(m["clips"][0]))
        with self.assertRaises(ValueError):
            validate_manifest(m)

    def test_exact_silence(self):
        with tempfile.TemporaryDirectory() as temp:
            path = Path(temp) / "clip.wav"
            write_pcm(path, struct.pack("<h", 900) * SAMPLE_RATE + bytes(3 * SAMPLE_RATE * 2))
            result = verify_tail(path, SAMPLE_RATE)
            self.assertEqual(result["tailPeakPcm16"], 0)
            self.assertEqual(result["durationSeconds"], 4)

    def test_source_leak_rejected(self):
        with tempfile.TemporaryDirectory() as temp:
            path = Path(temp) / "clip.wav"
            write_pcm(path, bytes(SAMPLE_RATE * 2) + struct.pack("<h", 900) * (3 * SAMPLE_RATE))
            with self.assertRaisesRegex(ValueError, "not silent"):
                verify_tail(path, SAMPLE_RATE)

    def test_short_padding_rejected(self):
        with tempfile.TemporaryDirectory() as temp:
            path = Path(temp) / "clip.wav"
            write_pcm(path, bytes(3 * SAMPLE_RATE * 2))
            with self.assertRaises(ValueError):
                verify_tail(path, SAMPLE_RATE)

    def test_output_not_overwritten(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source"
            ffmpeg = root / "ffmpeg"
            source.write_bytes(b"approved")
            ffmpeg.write_bytes(b"binary-placeholder")
            manifest = fixture_manifest()
            manifest["source"]["sha256"] = sha256(source)
            with self.assertRaises(FileExistsError):
                prepare(manifest, source, ffmpeg, root)

    def test_wrong_hash_before_ffmpeg(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source, ffmpeg = root / "source", root / "ffmpeg"
            source.write_bytes(b"not-approved")
            ffmpeg.write_bytes(b"placeholder")
            with self.assertRaisesRegex(ValueError, "SHA256"), patch("media.run_ffmpeg") as call:
                prepare(fixture_manifest(), source, ffmpeg, root / "new")
            call.assert_not_called()

    @unittest.skipUnless(os.environ.get("MEETING_BENCHMARK_FFMPEG"), "Explicit FFmpeg integration path not supplied")
    def test_generated_source_trim_precedes_padding(self):
        from media import run_ffmpeg
        executable = Path(os.environ["MEETING_BENCHMARK_FFMPEG"])
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            # Source changes from low to loud signal immediately AFTER requested end.
            # A trim-after-pad bug would leak the loud third/fourth second into the output.
            samples = b"".join(struct.pack("<h", value) * SAMPLE_RATE for value in (1000, 2000, 14000, 20000))
            source_wav = root / "original.wav"
            source_video = root / "original.mkv"
            write_pcm(source_wav, samples)
            run_ffmpeg(executable, ["-nostdin", "-loglevel", "error", "-n", "-f", "lavfi", "-i",
                                    "color=c=blue:s=64x64:r=25:d=4", "-i", str(source_wav),
                                    "-c:v", "ffv1", "-c:a", "pcm_s16le", str(source_video)], 30)
            manifest = fixture_manifest()
            manifest["source"]["sha256"] = sha256(source_video)
            report = prepare(manifest, source_video, executable, root / "clips", 30)
            pcm, frames = pcm_info(root / "clips" / "original-test.wav")
            self.assertEqual(frames, 4 * SAMPLE_RATE)
            self.assertEqual(pcm[:2 * SAMPLE_RATE], struct.pack("<h", 2000) * SAMPLE_RATE)
            self.assertEqual(pcm[2 * SAMPLE_RATE:], bytes(3 * SAMPLE_RATE * 2))
            self.assertEqual(report["clips"][0]["video"]["frames"], 100)
            self.assertTrue(report["clips"][0]["video"]["decodedAudioMatchesWav"])
            self.assertIsNone(report["clips"][0]["speechEnd"])


def add_invalid_manifest_case(name, mutate):
    def test(self):
        m = fixture_manifest()
        mutate(m)
        with self.assertRaises((ValueError, TypeError)):
            validate_manifest(m)
    setattr(MediaTests, "test_reject_" + name, test)


for name, mutate in {
    "schema": lambda m: m.update(schemaVersion=2),
    "hash": lambda m: m["source"].update(sha256="x"),
    "missing_license": lambda m: m["source"].pop("license"),
    "empty_attribution": lambda m: m["source"].update(attribution=[]),
    "http": lambda m: m["source"].update(url="http://example.invalid/x"),
    "empty_clips": lambda m: m.update(clips=[]),
    "path_id": lambda m: m["clips"][0].update(id="../escape"),
    "upper_id": lambda m: m["clips"][0].update(id="BAD"),
    "negative_start": lambda m: m["clips"][0].update(startSeconds=-1),
    "reversed": lambda m: m["clips"][0].update(endSeconds=0),
    "empty_interval": lambda m: m["clips"][0].update(endSeconds=1),
    "unbounded": lambda m: m["clips"][0].update(endSeconds=200),
    "fractional_frame": lambda m: m["clips"][0].update(endSeconds=2.001),
    "nan": lambda m: m["clips"][0].update(endSeconds=float("nan")),
    "infinity": lambda m: m["clips"][0].update(endSeconds=float("inf")),
    "bool_time": lambda m: m["clips"][0].update(startSeconds=True),
    "string_time": lambda m: m["clips"][0].update(startSeconds="1"),
    "guessed_acoustic": lambda m: m["clips"][0].update(speechEnd={"kind": "clip-boundary", "sourceSeconds": 2, "provenance": "guess"}),
    "missing_provenance": lambda m: m["clips"][0].update(speechEnd={"kind": "human-annotated", "sourceSeconds": 2}),
    "annotation_outside": lambda m: m["clips"][0].update(speechEnd={"kind": "human-annotated", "sourceSeconds": 3, "provenance": "operator"}),
}.items():
    add_invalid_manifest_case(name, mutate)


for tolerance in range(9):
    def test(self, tolerance=tolerance):
        with tempfile.TemporaryDirectory() as temp:
            path = Path(temp) / "clip.wav"
            write_pcm(path, bytes(SAMPLE_RATE * 2) + struct.pack("<h", tolerance) * (3 * SAMPLE_RATE))
            self.assertEqual(verify_tail(path, SAMPLE_RATE, tolerance)["tailPeakPcm16"], tolerance)
    setattr(MediaTests, f"test_tiny_pcm_tolerance_{tolerance}", test)


if __name__ == "__main__":
    unittest.main()
